### ISSUE TITLE
Support for proxy_cache would be nice

### ISSUE THREAD

**Issue by erasche** [galaxyproject/ansible-nginx#5]
Since the directory (sometimes) also needs to be created before nginx will write to it. Even pretty basic support would be sufficient.

```
nginx_proxy_caches:
  STATIC:
    location: /var/lib/nginx/cache
    conf: "levels=1:2 keys_zone=STATIC:10m inactive=24h  max_size=1g"
```
